# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-03 09:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_profile_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='poster_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='userId',
        ),
    ]
